// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqkcqzdkopcnjdllnyox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxa2NxemRrb3BjbmpkbGxueW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNDQ4OTYsImV4cCI6MjA1MzgyMDg5Nn0.r1cfEvfMXpqgqcUmC8vOMEppGmwyzO6nY2V1xJa_Sbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);